from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from time import sleep

serv_obj=Service("C:\Python_Selenium\Drivers\chromedriver.exe")
driver=webdriver.Chrome(service=serv_obj)
driver.get("https://demowebshop.tricentis.com/")
driver.maximize_window()
sleep(2)

driver.find_element("xpath","//ul[@class='top-menu']//a[@href='/apparel-shoes']").click()
sleep(2)
driver.find_element("partial link text","Digital").click()
sleep(2)
driver.find_element("xpath","//span[.='10.00']/../..//input[@value='Add to cart']").click()
sleep(2)


driver.find_element("xpath","//input[@value='Search store']").send_keys('laptop')
sleep(3)
driver.find_element('tag name','img').click()
sleep(2)
driver.find_element("css selector","input[value='2']").click()
sleep(2)
driver.find_element('id','newsletter-subscribe-button').click()
sleep(2)
driver.find_element("css selector","input[name='q']").send_keys('laptop')
sleep(3)

driver.find_element("css selector","input[value='Search']").click()
sleep(2)
driver.find_element("css selector","input[value='Add to cart']").click()
sleep(3)
# driver.find_element("css selector","span[class='cart-label']").click()
# sleep(2)
# driver.find_element("css selector",).click()
# sleep(2)
#
# driver.find_element("css selector","span[class='cart-label']").click()
# sleep(3)
# driver.find_element("css selector","input[type='checkbox']").click()
# sleep(3)
# driver.find_element("css selector","input[value='Update shopping cart']").click()
# sleep(3)

# driver.find_element("partial link text","Reg").click()
# sleep(3)
# driver.find_element("css selector","input[value='M']").click()
# sleep(3)
# driver.find_element("css selector","input[id='FirstName']").send_keys("krishna")
# sleep(3)
# driver.find_element("css selector","input[id='LastName']").send_keys("guna")
# sleep(3)
# driver.find_element("css selector","input[id='Email']").send_keys("krishnalela123@gmail.com")
# sleep(3)
# driver.find_element("css selector","input[id='Password']").send_keys("krishna")
# sleep(3)
# driver.find_element("css selector","input[id='ConfirmPassword']").send_keys("krishna")
# sleep(3)
# driver.find_element("css selector","input[id='register-button']").click()
# sleep(3)
# driver.find_element("partial link text","Log").click()
# sleep(3)
# driver.find_element("css selector","input[id='Email']").send_keys("krishnalela123@gmail.com")
# sleep(3)
# driver.find_element("css selector","input[id='Password']").send_keys("krishna")
# sleep(3)
# driver.find_element("name","RememberMe").click()
# sleep(3)
# driver.find_element("css selector","input[value='Log in']").click()
# sleep(3)
# driver.find_element("partial link text","out").click()
# sleep(3)

